INFO 2022-02-23 11:36:10,088 views Email Successfully Verified 79
INFO 2022-02-23 11:36:10,089 basehttp "GET /api/auth/otp-verify/ HTTP/1.1" 200 36 161
INFO 2022-02-23 12:25:01,924 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 12:25:10,345 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-23 12:25:12,840 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 12:25:54,192 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\urls.py changed, reloading. 251
INFO 2022-02-23 12:25:56,417 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 12:31:32,694 basehttp "POST /api/book/ HTTP/1.1" 201 202 161
INFO 2022-02-23 12:33:36,159 basehttp "PUT /api/book/ HTTP/1.1" 201 212 161
WARNING 2022-02-23 12:33:47,768 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:33:47,771 basehttp "GET /api/book/ HTTP/1.1" 400 29 161
WARNING 2022-02-23 12:33:57,454 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:33:57,455 basehttp "GET /api/book/ HTTP/1.1" 400 29 161
WARNING 2022-02-23 12:33:59,401 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:33:59,402 basehttp "GET /api/book/ HTTP/1.1" 400 29 161
INFO 2022-02-23 12:35:21,355 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 12:35:29,915 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 12:35:35,580 basehttp "GET /api/book/ HTTP/1.1" 201 1863 161
WARNING 2022-02-23 12:37:18,835 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:37:18,837 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 12:38:10,569 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 12:38:12,960 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 12:38:17,081 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:38:17,097 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:38:19,222 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:38:19,224 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:39:41,737 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:39:41,738 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:39:54,505 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:39:54,506 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:39:56,420 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:39:56,421 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 12:40:16,055 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 12:40:18,118 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 12:40:31,242 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:40:31,276 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:40:32,988 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:40:33,072 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:41:16,373 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:41:16,377 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-23 12:46:19,580 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 12:46:22,615 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 12:46:34,888 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:46:34,889 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:46:36,867 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:46:36,868 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 12:48:46,968 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 12:49:02,167 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:49:02,168 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 12:49:51,908 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 12:49:55,320 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 12:49:58,330 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:49:58,331 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:50:06,803 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:50:06,804 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-23 12:50:08,200 log Bad Request: /api/book/ 230
WARNING 2022-02-23 12:50:08,201 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 13:06:19,853 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 13:06:25,153 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 13:07:04,221 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 13:07:07,677 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 13:08:29,859 basehttp "DELETE /api/book/ HTTP/1.1" 204 26 161
WARNING 2022-02-23 13:09:29,085 log Bad Request: /api/book/ 230
WARNING 2022-02-23 13:09:29,086 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-23 13:10:25,453 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 13:10:29,650 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 13:10:36,045 basehttp "POST /api/book/ HTTP/1.1" 201 202 161
INFO 2022-02-23 13:11:15,562 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-23 13:11:22,620 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-23 13:12:00,931 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\models.py changed, reloading. 251
INFO 2022-02-23 13:12:03,951 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-23 13:20:15,310 log Bad Request: /api/book/ 230
WARNING 2022-02-23 13:20:15,346 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-24 17:33:41,037 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 17:39:38,240 basehttp "POST /api/auth/register/ HTTP/1.1" 201 35 161
INFO 2022-02-24 17:41:06,893 views Email Successfully Verified 79
INFO 2022-02-24 17:41:06,894 basehttp "GET /api/auth/otp-verify/ HTTP/1.1" 200 36 161
INFO 2022-02-24 17:41:23,587 basehttp "GET /api/book/ HTTP/1.1" 201 928 161
WARNING 2022-02-24 17:41:48,874 log Bad Request: /api/book/ 230
WARNING 2022-02-24 17:41:48,923 basehttp "PUT /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-24 17:43:17,281 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-24 17:43:19,752 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 17:43:48,112 basehttp "PUT /api/book/ HTTP/1.1" 201 213 161
INFO 2022-02-24 17:44:02,279 basehttp "GET /api/book/ HTTP/1.1" 201 937 161
WARNING 2022-02-24 17:45:22,014 log Bad Request: /api/book/ 230
WARNING 2022-02-24 17:45:22,025 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-24 17:45:36,446 basehttp "POST /api/book/ HTTP/1.1" 201 230 161
INFO 2022-02-24 17:45:53,976 basehttp "GET /api/book/ HTTP/1.1" 201 1123 161
INFO 2022-02-24 17:46:40,748 basehttp "DELETE /api/book/ HTTP/1.1" 204 26 161
INFO 2022-02-24 21:13:20,582 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 21:14:42,281 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\BookStoreApp\settings.py changed, reloading. 251
INFO 2022-02-24 21:14:45,111 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-24 21:17:01,655 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 103, in post
    encoded_token = EncodeDecodeToken.encode_token(user.pk)
NameError: name 'EncodeDecodeToken' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 112, in post
    except AuthenticationFailed:
NameError: name 'AuthenticationFailed' is not defined
ERROR 2022-02-24 21:17:01,659 basehttp "POST /api/auth/login HTTP/1.1" 500 98598 161
WARNING 2022-02-24 22:19:01,197 log Bad Request: /api/auth/login 230
WARNING 2022-02-24 22:19:01,197 basehttp "POST /api/auth/login HTTP/1.1" 400 34 161
INFO 2022-02-24 22:19:27,259 basehttp "POST /api/auth/register/ HTTP/1.1" 201 35 161
INFO 2022-02-24 22:25:18,936 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:25:22,244 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:27:18,263 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:27:20,658 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:28:54,795 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:28:57,389 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:29:53,164 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:29:56,164 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:30:23,921 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-24 22:30:48,109 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-24 22:30:48,109 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
WARNING 2022-02-24 22:30:57,744 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-24 22:30:57,745 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
ERROR 2022-02-24 22:31:15,064 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 102, in post
    user = auth.authenticate(username=username, password=password)
NameError: name 'auth' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 118, in post
    except AuthenticationFailed:
NameError: name 'AuthenticationFailed' is not defined
ERROR 2022-02-24 22:31:15,070 basehttp "POST /api/auth/login HTTP/1.1" 500 98423 161
INFO 2022-02-24 22:34:03,238 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:34:05,882 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:35:10,772 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:35:13,206 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:35:17,681 basehttp "POST /api/auth/login HTTP/1.1" 200 42 161
INFO 2022-02-24 22:36:37,228 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:36:39,382 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:36:44,890 basehttp "POST /api/auth/login HTTP/1.1" 200 55 161
INFO 2022-02-24 22:37:30,055 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:37:32,232 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:37:52,302 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:37:54,654 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:38:02,316 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-24 22:38:30,231 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-24 22:38:58,109 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-24 22:44:56,986 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:44:59,506 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:45:12,956 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-24 22:45:39,123 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:45:41,265 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:45:44,956 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-24 22:45:49,303 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-24 22:46:13,831 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:46:16,016 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 22:46:21,624 basehttp "POST /api/auth/login HTTP/1.1" 201 151 161
INFO 2022-02-24 22:46:51,156 basehttp "POST /api/auth/login HTTP/1.1" 201 151 161
INFO 2022-02-24 22:47:16,784 basehttp "POST /api/auth/login HTTP/1.1" 201 151 161
INFO 2022-02-24 22:48:36,884 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-24 22:48:39,156 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-24 23:13:07,335 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-24 23:13:21,726 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-24 23:13:52,584 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 10:40:24,750 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-25 10:40:29,397 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 10:41:10,262 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-25 10:41:13,817 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 10:41:57,550 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-25 10:41:59,985 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 10:42:25,281 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-25 10:42:27,907 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 10:45:17,145 log Not Found: /api/auth/login/ 230
WARNING 2022-02-25 10:45:17,159 basehttp "POST /api/auth/login/ HTTP/1.1" 404 2781 161
INFO 2022-02-25 10:46:20,632 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 10:47:13,741 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 10:47:27,644 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 10:48:05,657 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 10:48:37,115 basehttp "POST /api/auth/login HTTP/1.1" 201 143 161
INFO 2022-02-25 12:30:38,693 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\BookStoreApp\settings.py changed, reloading. 251
INFO 2022-02-25 12:30:42,320 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 12:32:16,369 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\BookStoreApp\settings.py changed, reloading. 251
INFO 2022-02-25 12:32:18,953 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 12:40:41,570 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 12:42:32,061 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\BookStoreApp\settings.py changed, reloading. 251
INFO 2022-02-25 12:42:34,262 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 12:45:13,027 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 12:46:23,071 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 12:46:30,007 log Not Found: /api/auth/login/ 230
WARNING 2022-02-25 12:46:30,008 basehttp "POST /api/auth/login/ HTTP/1.1" 404 2781 161
WARNING 2022-02-25 12:46:33,966 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:46:33,967 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
WARNING 2022-02-25 12:46:49,054 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:46:49,055 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
INFO 2022-02-25 12:47:01,776 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 12:47:29,901 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
WARNING 2022-02-25 12:47:46,178 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:47:46,180 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
WARNING 2022-02-25 12:47:48,056 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:47:48,062 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
WARNING 2022-02-25 12:47:57,793 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:47:57,793 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
WARNING 2022-02-25 12:47:59,474 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 12:47:59,477 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
INFO 2022-02-25 12:48:22,614 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 12:48:48,531 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 12:51:14,498 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 13:00:32,073 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 13:23:07,009 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 13:23:09,256 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 13:24:41,812 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\BookStoreApp\settings.py changed, reloading. 251
INFO 2022-02-25 13:24:43,966 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 13:24:50,782 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-25 13:26:33,801 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 13:27:29,842 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-25 13:28:11,025 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
INFO 2022-02-25 13:28:27,338 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
WARNING 2022-02-25 13:32:01,186 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:32:01,187 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
WARNING 2022-02-25 13:32:15,487 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:32:15,488 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
INFO 2022-02-25 13:32:40,110 basehttp "POST /api/auth/login HTTP/1.1" 202 155 161
WARNING 2022-02-25 13:32:57,547 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:32:57,549 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
INFO 2022-02-25 13:33:52,415 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 13:33:55,514 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 13:34:02,434 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:34:02,434 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
INFO 2022-02-25 13:34:17,603 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
WARNING 2022-02-25 13:35:28,647 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:35:28,647 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
WARNING 2022-02-25 13:53:14,725 log Unauthorized: /api/auth/login 230
WARNING 2022-02-25 13:53:14,727 basehttp "POST /api/auth/login HTTP/1.1" 401 183 161
INFO 2022-02-25 13:53:34,475 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 13:54:24,310 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 13:59:12,566 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 13:59:15,056 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:00:32,230 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:00:36,352 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:04:39,432 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:04:42,733 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:05:34,549 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:05:39,440 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:08:14,359 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 14:08:16,946 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:10:41,637 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:10:43,998 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:10:58,444 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:11:15,065 log Not Found: /api/auth/reg 230
WARNING 2022-02-25 14:11:15,066 basehttp "POST /api/auth/reg HTTP/1.1" 404 2772 161
WARNING 2022-02-25 14:11:28,262 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-25 14:11:28,263 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
WARNING 2022-02-25 14:11:54,415 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-25 14:11:54,415 basehttp "POST /api/auth/register/ HTTP/1.1" 400 30 161
WARNING 2022-02-25 14:12:06,022 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-25 14:12:06,023 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
INFO 2022-02-25 14:14:19,403 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 14:14:22,111 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:14:53,094 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-25 14:16:05,572 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:16:07,628 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:16:22,756 basehttp "POST /api/auth/login HTTP/1.1" 201 146 161
INFO 2022-02-25 14:25:01,370 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:25:03,812 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:25:51,327 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:25:53,759 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:26:37,874 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:26:40,135 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:26:46,448 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 14:26:46,449 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
WARNING 2022-02-25 14:26:51,024 log Bad Request: /api/auth/login 230
WARNING 2022-02-25 14:26:51,024 basehttp "POST /api/auth/login HTTP/1.1" 400 36 161
INFO 2022-02-25 14:28:06,693 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:28:09,124 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:28:13,899 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:28:13,900 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
WARNING 2022-02-25 14:28:40,004 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:28:40,035 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:28:55,200 basehttp "POST /api/auth/register/ HTTP/1.1" 201 35 161
WARNING 2022-02-25 14:29:07,359 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-25 14:29:07,359 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
WARNING 2022-02-25 14:29:18,129 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:29:18,129 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:32:07,227 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:32:09,737 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:32:14,132 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:32:14,134 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:32:40,127 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:32:42,843 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:33:08,968 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:33:08,969 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:34:52,989 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:34:55,047 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:35:36,746 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:35:38,882 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:35:46,931 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:35:46,932 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:36:13,611 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:36:15,931 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:36:19,708 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:37:52,971 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 14:37:56,107 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:38:06,093 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:38:32,463 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:39:01,155 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:39:26,541 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 14:39:29,236 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:39:35,076 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:39:48,968 basehttp "POST /api/auth/login HTTP/1.1" 201 147 161
INFO 2022-02-25 14:42:42,173 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:42:44,580 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 14:42:49,561 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:42:49,563 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
WARNING 2022-02-25 14:42:56,410 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:42:56,412 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
WARNING 2022-02-25 14:42:58,617 log Not Found: /api/auth/login 230
WARNING 2022-02-25 14:42:58,617 basehttp "POST /api/auth/login HTTP/1.1" 404 33 161
INFO 2022-02-25 14:43:51,716 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:43:54,446 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:44:43,044 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:44:45,101 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:44:49,420 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:45:12,576 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:47:44,247 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:47:46,569 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:47:51,247 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:48:07,431 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:53:20,603 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:53:23,457 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:56:18,693 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 14:56:21,554 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:57:04,000 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 14:57:06,624 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:57:27,156 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 14:57:29,397 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 14:57:38,779 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:57:47,236 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:57:59,174 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:58:02,155 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 14:58:09,391 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
WARNING 2022-02-25 14:58:40,438 log Method Not Allowed: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
WARNING 2022-02-25 14:58:40,439 basehttp "POST /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 405 41 161
INFO 2022-02-25 14:58:47,947 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 201 36 161
INFO 2022-02-25 15:01:38,311 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:01:40,776 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:04:43,989 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:04:46,103 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 15:05:09,488 log Method Not Allowed: /api/auth/login 230
WARNING 2022-02-25 15:05:09,489 basehttp "GET /api/auth/login HTTP/1.1" 405 40 161
INFO 2022-02-25 15:05:17,565 basehttp "POST /api/auth/login HTTP/1.1" 202 270 161
INFO 2022-02-25 15:09:15,960 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:09:18,225 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:09:22,678 basehttp "POST /api/auth/login HTTP/1.1" 202 270 161
INFO 2022-02-25 15:09:25,002 basehttp "POST /api/auth/login HTTP/1.1" 202 270 161
INFO 2022-02-25 15:10:23,695 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:10:26,233 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:10:29,341 basehttp "POST /api/auth/login HTTP/1.1" 202 284 161
INFO 2022-02-25 15:11:25,168 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:11:28,025 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:11:29,976 basehttp "POST /api/auth/login HTTP/1.1" 200 79 161
INFO 2022-02-25 15:13:44,304 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:13:48,830 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:14:29,081 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:14:31,331 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:14:38,210 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
INFO 2022-02-25 15:16:03,059 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:16:05,382 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:16:09,904 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-25 15:16:31,078 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:16:33,704 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:16:38,124 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 15:16:54,839 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:16:56,826 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:17:03,650 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 15:17:06,309 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 15:18:00,766 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:18:03,764 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:18:08,313 basehttp "POST /api/auth/login HTTP/1.1" 200 39 161
INFO 2022-02-25 15:19:16,423 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:19:18,505 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:19:23,864 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:24:51,727 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:24:53,707 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:24:58,854 basehttp "POST /api/auth/login HTTP/1.1" 202 279 161
INFO 2022-02-25 15:25:08,559 basehttp "POST /api/auth/login HTTP/1.1" 202 279 161
INFO 2022-02-25 15:27:54,674 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:27:57,171 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:28:01,813 basehttp "POST /api/auth/login HTTP/1.1" 200 41 161
INFO 2022-02-25 15:28:30,711 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:28:33,469 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:28:41,508 basehttp "POST /api/auth/login HTTP/1.1" 200 41 161
INFO 2022-02-25 15:28:43,603 basehttp "POST /api/auth/login HTTP/1.1" 200 41 161
INFO 2022-02-25 15:29:09,807 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:29:11,919 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:29:18,139 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 15:30:38,327 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:30:42,782 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:30:57,133 basehttp "POST /api/auth/login HTTP/1.1" 202 279 161
INFO 2022-02-25 15:31:28,442 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:31:30,487 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:31:35,952 basehttp "POST /api/auth/login HTTP/1.1" 202 268 161
INFO 2022-02-25 15:35:07,648 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:35:09,860 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:35:14,901 basehttp "POST /api/auth/login HTTP/1.1" 200 52 161
INFO 2022-02-25 15:35:36,424 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:35:38,648 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:35:42,192 basehttp "POST /api/auth/login HTTP/1.1" 200 66 161
INFO 2022-02-25 15:36:17,862 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:36:20,162 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:36:25,254 basehttp "POST /api/auth/login HTTP/1.1" 200 63 161
INFO 2022-02-25 15:36:49,014 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:36:51,328 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:36:56,462 basehttp "POST /api/auth/login HTTP/1.1" 200 53 161
INFO 2022-02-25 15:37:21,721 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:37:24,021 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:37:29,399 basehttp "POST /api/auth/login HTTP/1.1" 200 43 161
INFO 2022-02-25 15:37:39,801 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:37:42,030 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:37:47,224 basehttp "POST /api/auth/login HTTP/1.1" 200 52 161
INFO 2022-02-25 15:37:59,003 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:38:01,819 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 15:38:08,180 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
ERROR 2022-02-25 15:38:08,197 basehttp "POST /api/auth/login HTTP/1.1" 500 105444 161
INFO 2022-02-25 15:38:58,741 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:39:00,919 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:39:07,328 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:39:43,452 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:39:45,528 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:39:51,551 basehttp "POST /api/auth/login HTTP/1.1" 200 78 161
INFO 2022-02-25 15:40:48,504 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:40:50,719 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 15:40:55,353 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
ERROR 2022-02-25 15:40:55,359 basehttp "POST /api/auth/login HTTP/1.1" 500 105291 161
INFO 2022-02-25 15:42:05,405 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:42:08,700 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:42:42,836 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:42:44,837 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:42:49,379 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:44:54,970 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:44:57,072 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:46:16,105 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:46:22,231 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:47:16,992 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:47:19,212 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:47:23,404 basehttp "POST /api/auth/login HTTP/1.1" 200 38 161
INFO 2022-02-25 15:47:56,394 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:47:58,643 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:49:34,012 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:49:37,223 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:49:41,738 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:51:42,481 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:51:44,423 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:51:54,101 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 15:51:56,054 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:52:01,067 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:55:26,994 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:55:29,055 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:55:34,115 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 15:56:30,663 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:56:33,737 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:56:43,016 basehttp "POST /api/auth/login HTTP/1.1" 200 53 161
INFO 2022-02-25 15:57:31,960 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 15:57:34,005 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:57:38,442 basehttp "POST /api/auth/login HTTP/1.1" 202 193 161
INFO 2022-02-25 15:58:05,504 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:58:08,134 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:59:10,177 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:59:12,929 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:59:16,689 basehttp "POST /api/auth/login HTTP/1.1" 200 70 161
INFO 2022-02-25 15:59:32,393 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:59:34,828 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 15:59:38,682 basehttp "POST /api/auth/login HTTP/1.1" 200 70 161
INFO 2022-02-25 15:59:54,956 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 15:59:57,126 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:00:01,112 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 16:01:07,966 basehttp "POST /api/auth/login HTTP/1.1" 200 45 161
INFO 2022-02-25 16:02:37,240 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 16:02:39,816 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:02:48,697 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 16:07:26,832 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:07:29,767 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:07:48,428 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:07:52,272 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:07:58,914 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
WARNING 2022-02-25 16:09:01,081 log Not Found: /user/validate/ 230
WARNING 2022-02-25 16:09:01,081 basehttp "POST /user/validate/ HTTP/1.1" 404 2344 161
WARNING 2022-02-25 16:09:17,897 log Not Found: /user/login 230
WARNING 2022-02-25 16:09:17,897 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:09:19,711 log Not Found: /user/login 230
WARNING 2022-02-25 16:09:19,712 basehttp "POST /user/login HTTP/1.1" 404 2332 161
INFO 2022-02-25 16:10:21,758 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:10:25,222 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:10:27,878 log Not Found: /user/login 230
WARNING 2022-02-25 16:10:27,880 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:10:29,577 log Not Found: /user/login 230
WARNING 2022-02-25 16:10:29,577 basehttp "POST /user/login HTTP/1.1" 404 2332 161
INFO 2022-02-25 16:11:23,999 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:11:29,078 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:12:56,653 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:12:59,956 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:13:44,659 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:13:47,241 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:13:53,948 log Not Found: /user/login 230
WARNING 2022-02-25 16:13:53,948 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:13:55,941 log Not Found: /user/login 230
WARNING 2022-02-25 16:13:55,942 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:14:25,597 log Not Found: /user/login 230
WARNING 2022-02-25 16:14:25,597 basehttp "POST /user/login HTTP/1.1" 404 2332 161
INFO 2022-02-25 16:14:40,666 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:14:43,859 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:15:01,701 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:15:05,321 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:15:09,201 log Not Found: /user/login 230
WARNING 2022-02-25 16:15:09,202 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:15:11,305 log Not Found: /user/login 230
WARNING 2022-02-25 16:15:11,306 basehttp "POST /user/login HTTP/1.1" 404 2332 161
WARNING 2022-02-25 16:15:43,172 log Not Found: /api/auth/login/ 230
WARNING 2022-02-25 16:15:43,173 basehttp "POST /api/auth/login/ HTTP/1.1" 404 2781 161
INFO 2022-02-25 16:15:50,530 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
INFO 2022-02-25 16:17:07,345 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:17:11,196 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:17:48,927 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:17:52,076 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:18:09,852 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:18:14,467 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:18:43,107 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:18:54,737 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:18:57,776 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:19:02,425 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
WARNING 2022-02-25 16:19:21,199 log Method Not Allowed: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
WARNING 2022-02-25 16:19:21,200 basehttp "POST /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 405 41 161
ERROR 2022-02-25 16:19:26,714 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 134, in get
    decoded_token = EncodeDecodeToken.decode_token(token=encoded_token)
NameError: name 'encoded_token' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 143, in get
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 16:19:26,738 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 99981 161
INFO 2022-02-25 16:19:58,207 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:20:03,214 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:20:09,762 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 134, in get
    decoded_token = EncodeDecodeToken.decode_token(token=token)
TypeError: decode_token() got an unexpected keyword argument 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 143, in get
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 16:20:09,850 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 100009 161
INFO 2022-02-25 16:21:11,495 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:21:13,848 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:21:18,738 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'token'
ERROR 2022-02-25 16:21:18,744 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 92242 161
ERROR 2022-02-25 16:21:59,371 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'token'
ERROR 2022-02-25 16:21:59,382 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 92234 161
WARNING 2022-02-25 16:22:11,755 log Method Not Allowed: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
WARNING 2022-02-25 16:22:11,757 basehttp "POST /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 405 41 161
INFO 2022-02-25 16:22:21,794 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
ERROR 2022-02-25 16:22:55,767 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'token'
ERROR 2022-02-25 16:22:55,769 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 92234 161
INFO 2022-02-25 16:23:26,008 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:23:29,098 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:23:34,370 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'token'
ERROR 2022-02-25 16:23:34,410 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 92234 161
INFO 2022-02-25 16:24:51,541 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:24:59,854 basehttp "POST /api/auth/login HTTP/1.1" 202 191 161
ERROR 2022-02-25 16:26:26,932 log Internal Server Error: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'token'
ERROR 2022-02-25 16:26:26,940 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 500 92234 161
INFO 2022-02-25 16:27:39,876 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:27:43,393 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:28:38,573 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:28:45,608 log Not Found: /api/auth/"validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:28:45,640 basehttp "GET /api/auth/%22validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3318 161
INFO 2022-02-25 16:31:40,884 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:31:45,507 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:32:36,174 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:32:38,728 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:32:44,942 log Not Found: /api/auth/"validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:32:44,944 basehttp "GET /api/auth/%22validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3317 161
WARNING 2022-02-25 16:32:57,272 log Not Found: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:32:57,274 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3317 161
WARNING 2022-02-25 16:32:59,840 log Not Found: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:32:59,840 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3317 161
INFO 2022-02-25 16:33:55,865 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:33:58,509 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:51:04,555 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:51:06,672 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:51:12,644 log Not Found: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:51:12,645 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3317 161
INFO 2022-02-25 16:51:30,048 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:51:32,283 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:51:57,246 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
WARNING 2022-02-25 16:52:27,774 log Not Found: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
WARNING 2022-02-25 16:52:27,775 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 404 3300 161
INFO 2022-02-25 16:52:36,946 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 16:52:39,369 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:52:52,144 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'encoded_token'
ERROR 2022-02-25 16:52:52,147 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 90035 161
INFO 2022-02-25 16:52:56,816 basehttp "GET /api/auth/validate HTTP/1.1" 301 0 161
ERROR 2022-02-25 16:52:56,918 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'encoded_token'
ERROR 2022-02-25 16:52:56,934 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 90187 161
INFO 2022-02-25 16:53:24,101 basehttp "GET /api/auth/validate HTTP/1.1" 301 0 161
ERROR 2022-02-25 16:53:24,207 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'encoded_token'
ERROR 2022-02-25 16:53:24,209 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 90187 161
INFO 2022-02-25 16:53:45,690 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:53:48,089 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 16:53:52,023 basehttp "GET /api/auth/validate HTTP/1.1" 301 0 161
ERROR 2022-02-25 16:53:52,150 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'encoded_token'
ERROR 2022-02-25 16:53:52,157 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 90187 161
ERROR 2022-02-25 16:54:04,797 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'encoded_token'
ERROR 2022-02-25 16:54:04,799 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 90035 161
INFO 2022-02-25 16:55:06,531 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:55:09,586 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:55:18,563 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 134, in get
    decoded_token = EncodeDecodeToken.decode_token(token=encoded_token)
NameError: name 'encoded_token' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 143, in get
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 16:55:18,577 basehttp "GET /api/auth/validate/ HTTP/1.1" 500 96995 161
INFO 2022-02-25 16:56:39,742 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:56:41,843 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 16:56:46,263 log Method Not Allowed: /api/auth/validate/ 230
WARNING 2022-02-25 16:56:46,268 basehttp "GET /api/auth/validate/ HTTP/1.1" 405 40 161
ERROR 2022-02-25 16:56:52,315 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 134, in post
    decoded_token = EncodeDecodeToken.decode_token(self.request.data)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 177, in _load
    binary_type))
jwt.exceptions.DecodeError: Invalid token type. Token must be a <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 143, in post
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 16:56:52,323 basehttp "POST /api/auth/validate/ HTTP/1.1" 500 109098 161
ERROR 2022-02-25 16:57:28,135 log Internal Server Error: /api/auth/validate 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\middleware\common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/auth/validate/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-02-25 16:57:28,139 basehttp "POST /api/auth/validate HTTP/1.1" 500 72758 161
ERROR 2022-02-25 16:57:45,812 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 134, in post
    decoded_token = EncodeDecodeToken.decode_token(self.request.data)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 177, in _load
    binary_type))
jwt.exceptions.DecodeError: Invalid token type. Token must be a <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 143, in post
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 16:57:45,817 basehttp "POST /api/auth/validate/ HTTP/1.1" 500 109098 161
INFO 2022-02-25 16:59:23,900 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 16:59:26,557 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 16:59:32,367 log Internal Server Error: /api/auth/validate/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DecodeError' is not JSON serializable
ERROR 2022-02-25 16:59:32,375 basehttp "POST /api/auth/validate/ HTTP/1.1" 500 103255 161
INFO 2022-02-25 17:03:54,552 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 17:03:56,869 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 17:04:26,553 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 17:04:28,658 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-25 17:04:34,275 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-25 17:04:34,276 basehttp "POST /api/auth/validate/ HTTP/1.1" 404 2988 161
WARNING 2022-02-25 17:04:36,155 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-25 17:04:36,156 basehttp "POST /api/auth/validate/ HTTP/1.1" 404 2988 161
INFO 2022-02-25 17:04:43,332 basehttp "POST /api/auth/login HTTP/1.1" 202 156 161
WARNING 2022-02-25 17:05:09,123 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY 230
WARNING 2022-02-25 17:05:09,124 basehttp "POST /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 404 3288 161
INFO 2022-02-25 17:05:28,129 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 17:05:31,082 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 17:06:02,127 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-25 17:06:04,312 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 17:06:13,381 log Internal Server Error: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 204, in _load
    signature = base64url_decode(crypto_segment)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 132, in post
    decoded_token = EncodeDecodeToken.decode_token(eroded_token=token)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 206, in _load
    raise DecodeError('Invalid crypto padding')
jwt.exceptions.DecodeError: Invalid crypto padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 141, in post
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 17:06:13,401 basehttp "POST /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 500 130858 161
INFO 2022-02-25 17:06:30,520 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 17:06:32,587 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 17:06:38,900 log Internal Server Error: /api/auth/validate/"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY" 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 204, in _load
    signature = base64url_decode(crypto_segment)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 132, in get
    decoded_token = EncodeDecodeToken.decode_token(eroded_token=token)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 206, in _load
    raise DecodeError('Invalid crypto padding')
jwt.exceptions.DecodeError: Invalid crypto padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py", line 141, in get
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-25 17:06:38,912 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 500 130837 161
INFO 2022-02-25 17:07:45,314 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 17:07:47,448 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 17:07:52,833 basehttp "GET /api/auth/validate/%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY%22 HTTP/1.1" 200 22 161
INFO 2022-02-25 17:08:04,163 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 201 36 161
INFO 2022-02-25 21:04:10,774 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:04:30,357 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:07:26,554 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:07:28,851 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:07:59,398 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:08:02,526 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:08:13,024 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:08:15,500 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-25 21:08:29,018 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2022-02-25 21:08:29,037 basehttp "POST /api/auth/login HTTP/1.1" 500 81228 161
INFO 2022-02-25 21:08:48,784 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:08:57,144 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:09:23,258 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:09:25,740 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:09:33,498 basehttp "POST /api/auth/login HTTP/1.1" 202 157 161
INFO 2022-02-25 21:13:18,414 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:13:20,853 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:13:27,423 basehttp "POST /api/auth/login HTTP/1.1" 202 311 161
INFO 2022-02-25 21:14:17,590 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:14:21,159 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:14:35,598 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:14:38,381 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:19:02,552 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:19:05,460 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:21:03,600 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:21:22,808 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 200 35 161
INFO 2022-02-25 21:22:27,880 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:22:31,013 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:22:40,146 basehttp "POST /api/auth/login HTTP/1.1" 202 157 161
INFO 2022-02-25 21:22:45,331 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 200 35 161
INFO 2022-02-25 21:22:47,318 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.m4LJcbC8GTCxpjf-ZG-6KULVNpin6kaRrBRl-tIXSmY HTTP/1.1" 200 35 161
INFO 2022-02-25 21:23:03,048 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoidmluYSJ9.w62o5acTWuySQpkoNRZRO7EJ4GEHVPidi61D3ztG1Xo HTTP/1.1" 200 35 161
INFO 2022-02-25 21:23:22,591 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 21:23:25,440 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:23:30,269 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoidmluYSJ9.w62o5acTWuySQpkoNRZRO7EJ4GEHVPidi61D3ztG1Xo HTTP/1.1" 200 35 161
INFO 2022-02-25 21:23:32,317 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoidmluYSJ9.w62o5acTWuySQpkoNRZRO7EJ4GEHVPidi61D3ztG1Xo HTTP/1.1" 200 35 161
INFO 2022-02-25 21:24:38,914 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 21:24:46,592 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:26:03,699 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoidmluYSJ9.w62o5acTWuySQpkoNRZRO7EJ4GEHVPidi61D3ztG1Xo HTTP/1.1" 200 35 161
INFO 2022-02-25 21:27:10,597 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-25 21:27:13,737 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:27:27,304 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-25 21:28:51,633 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:28:54,614 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:29:16,176 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:29:19,038 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:29:24,294 basehttp "POST /api/auth/login HTTP/1.1" 200 62 161
INFO 2022-02-25 21:29:40,695 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:29:43,022 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-25 21:29:48,844 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-25 21:30:12,666 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 36 161
INFO 2022-02-25 21:40:38,468 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-25 21:40:44,215 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 09:40:59,160 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 09:48:37,843 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 7 161
INFO 2022-02-26 09:48:40,286 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 7 161
INFO 2022-02-26 09:48:53,727 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 7 161
INFO 2022-02-26 09:49:04,139 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 09:49:07,752 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 09:49:16,690 basehttp "GET /api/auth/validate/yJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 200 93 161
INFO 2022-02-26 09:49:38,149 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 36 161
INFO 2022-02-26 09:50:38,101 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 09:50:41,700 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 10:23:42,315 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:23:45,480 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 10:27:27,423 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:27:29,475 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 10:27:45,198 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:27:47,259 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 10:27:53,860 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ 230
WARNING 2022-02-26 10:27:53,861 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 404 3331 161
INFO 2022-02-26 10:29:50,857 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:29:53,071 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 10:29:57,907 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ 230
WARNING 2022-02-26 10:29:57,911 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 404 3333 161
INFO 2022-02-26 10:31:29,455 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:31:31,688 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 10:31:36,062 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ 230
WARNING 2022-02-26 10:31:36,063 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 404 3327 161
WARNING 2022-02-26 10:31:38,330 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ 230
WARNING 2022-02-26 10:31:38,331 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 404 3327 161
WARNING 2022-02-26 10:31:40,442 log Not Found: /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ 230
WARNING 2022-02-26 10:31:40,443 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 404 3327 161
INFO 2022-02-26 10:32:24,153 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 10:32:26,725 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 10:32:31,267 basehttp "GET /api/auth/validate/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZpbmEifQ.FY2dI-P7hGCrtDHikQU5CI_xHMxPWZm8BikTF7I1YnQ HTTP/1.1" 201 36 161
INFO 2022-02-26 11:28:24,871 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 11:28:28,852 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 11:49:09,011 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 11:49:13,318 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 11:50:24,947 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 11:50:27,933 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 11:51:33,498 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 11:51:37,075 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 11:52:52,808 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 11:52:55,051 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 11:53:50,588 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\models.py changed, reloading. 251
INFO 2022-02-26 11:53:52,587 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:03:27,555 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-26 12:03:30,341 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:05:12,282 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
ERROR 2022-02-26 12:06:02,794 log Internal Server Error: /api/book/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\utility.py", line 9, in wrapper
    user_id = EncodeDecodeToken.decode_token(token)
NameError: name 'EncodeDecodeToken' is not defined
ERROR 2022-02-26 12:06:02,800 basehttp "POST /api/book/ HTTP/1.1" 500 94529 161
INFO 2022-02-26 12:07:58,986 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-26 12:08:04,353 log Internal Server Error: /api/book/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\utility.py", line 9, in wrapper
    user_id = EncodeDecodeToken.decode_token(token)
NameError: name 'EncodeDecodeToken' is not defined
ERROR 2022-02-26 12:08:04,426 basehttp "POST /api/book/ HTTP/1.1" 500 94529 161
INFO 2022-02-26 12:10:01,854 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\utility.py changed, reloading. 251
INFO 2022-02-26 12:10:04,063 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:10:20,127 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\utility.py changed, reloading. 251
INFO 2022-02-26 12:10:22,370 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 12:10:31,419 log Bad Request: /api/book/ 230
WARNING 2022-02-26 12:10:31,421 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-26 12:10:52,822 log Bad Request: /api/book/ 230
WARNING 2022-02-26 12:10:52,823 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-26 12:12:24,349 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\utility.py changed, reloading. 251
INFO 2022-02-26 12:12:26,600 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 12:12:30,829 log Bad Request: /api/book/ 230
WARNING 2022-02-26 12:12:30,831 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-26 12:55:13,118 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-26 12:55:15,490 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:58:36,286 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 12:58:39,426 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:58:55,973 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 12:58:57,931 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 12:59:22,966 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 12:59:25,018 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:00:15,568 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 13:00:18,040 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 13:00:42,206 log Method Not Allowed: /api/auth/login 230
WARNING 2022-02-26 13:00:42,206 basehttp "POST /api/auth/login HTTP/1.1" 405 41 161
WARNING 2022-02-26 13:00:48,106 log Bad Request: /api/auth/login 230
WARNING 2022-02-26 13:00:48,116 basehttp "GET /api/auth/login HTTP/1.1" 400 46 161
INFO 2022-02-26 13:01:02,890 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 13:01:04,929 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 13:01:09,208 log Method Not Allowed: /api/auth/login 230
WARNING 2022-02-26 13:01:09,209 basehttp "GET /api/auth/login HTTP/1.1" 405 40 161
WARNING 2022-02-26 13:01:15,332 log Bad Request: /api/auth/login 230
WARNING 2022-02-26 13:01:15,333 basehttp "POST /api/auth/login HTTP/1.1" 400 46 161
INFO 2022-02-26 13:02:54,136 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 13:02:56,186 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:02:59,533 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 13:03:16,837 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 13:03:31,857 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 13:08:19,992 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 13:08:22,997 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:09:15,836 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 13:09:20,013 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:15:40,897 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 13:15:43,550 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:22:18,907 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 13:22:21,477 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:22:28,393 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 13:22:33,702 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
WARNING 2022-02-26 13:22:54,511 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:22:54,512 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2789 161
INFO 2022-02-26 13:23:15,426 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 13:23:18,092 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:23:33,552 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 13:23:35,658 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 13:23:50,573 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 13:23:52,790 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 13:23:56,873 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:23:56,873 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:23:58,639 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:23:58,641 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
INFO 2022-02-26 13:24:40,633 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
WARNING 2022-02-26 13:24:54,026 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:24:54,026 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:24:55,869 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:24:55,877 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:25:19,405 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:25:19,409 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:25:30,193 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:25:30,197 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:25:31,606 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:25:31,607 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
INFO 2022-02-26 13:26:22,807 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 13:26:24,921 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-26 13:26:31,181 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:26:31,182 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:26:32,578 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:26:32,578 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 13:26:40,949 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 13:26:40,950 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
WARNING 2022-02-26 14:01:32,772 log Not Found: /api/auth/validate/ 230
WARNING 2022-02-26 14:01:32,773 basehttp "GET /api/auth/validate/ HTTP/1.1" 404 2970 161
INFO 2022-02-26 14:02:00,385 basehttp "GET /api/auth/validate HTTP/1.1" 201 36 161
INFO 2022-02-26 14:04:44,139 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 14:59:00,182 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 14:59:03,549 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 14:59:23,594 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 14:59:25,579 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:00:23,332 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 15:00:26,341 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:01:29,850 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\urls.py changed, reloading. 251
INFO 2022-02-26 15:01:32,337 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-26 15:02:04,961 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 186, in _load
    header_data = base64url_decode(header_segment)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 47, in wrapper
    user_id = EncodeDecodeToken.decode_token(token)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 188, in _load
    raise DecodeError('Invalid header padding')
jwt.exceptions.DecodeError: Invalid header padding
ERROR 2022-02-26 15:02:04,969 basehttp "POST /api/auth/login HTTP/1.1" 500 124571 161
ERROR 2022-02-26 15:02:24,532 log Internal Server Error: /api/auth/login 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 186, in _load
    header_data = base64url_decode(header_segment)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Users\CHANDRU\AppData\Local\Programs\Python\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 47, in wrapper
    user_id = EncodeDecodeToken.decode_token(token)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py", line 35, in decode_token
    algorithms="HS256"
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\jwt\api_jws.py", line 188, in _load
    raise DecodeError('Invalid header padding')
jwt.exceptions.DecodeError: Invalid header padding
ERROR 2022-02-26 15:02:24,535 basehttp "POST /api/auth/login HTTP/1.1" 500 124571 161
INFO 2022-02-26 15:22:16,431 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 15:22:18,823 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:24:12,881 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 15:24:16,035 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:30:45,036 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 15:30:48,793 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:39:54,721 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 15:39:57,188 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:40:09,044 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 15:40:18,591 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:40:37,096 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 15:40:39,381 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:40:55,239 basehttp "POST /api/auth/login HTTP/1.1" 200 77 161
INFO 2022-02-26 15:42:16,796 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-26 15:42:19,610 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:42:25,330 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 15:43:04,441 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
INFO 2022-02-26 15:43:43,748 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
WARNING 2022-02-26 15:46:14,313 log Bad Request: /api/book/ 230
WARNING 2022-02-26 15:46:14,314 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-26 15:47:02,332 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\models.py changed, reloading. 251
INFO 2022-02-26 15:47:05,698 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:48:13,885 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 15:48:16,670 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 15:48:23,602 basehttp "POST /api/book/ HTTP/1.1" 201 238 161
INFO 2022-02-26 16:01:39,331 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\serializers.py changed, reloading. 251
INFO 2022-02-26 16:01:44,509 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-26 16:07:15,717 basehttp "POST /api/auth/login HTTP/1.1" 202 163 161
WARNING 2022-02-26 16:07:55,806 log Bad Request: /api/book/ 230
WARNING 2022-02-26 16:07:55,807 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-26 16:25:53,905 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-26 16:25:56,577 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 15:37:25,843 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 15:37:29,918 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 16:24:21,504 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-27 16:24:24,760 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 16:30:13,134 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 16:30:15,557 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 16:32:59,336 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 16:33:02,248 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 19:07:11,980 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:07:15,117 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 19:07:23,894 basehttp "POST /api/auth/login HTTP/1.1" 200 56 161
INFO 2022-02-27 19:12:36,853 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-27 19:12:38,822 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 19:12:43,330 basehttp "POST /api/auth/login HTTP/1.1" 202 149 161
WARNING 2022-02-27 19:13:04,542 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:13:04,554 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:13:06,560 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:13:06,561 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:14:41,916 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 19:14:43,825 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:15:00,972 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:15:00,972 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:15:11,061 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:15:11,062 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:15:48,839 basehttp "POST /api/auth/login HTTP/1.1" 202 149 161
WARNING 2022-02-27 19:16:00,995 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:16:00,996 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:16:52,555 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:16:54,800 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:16:58,429 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:16:58,432 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:19:10,432 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:19:15,291 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:19:15,295 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:21:44,525 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\views.py changed, reloading. 251
INFO 2022-02-27 19:21:46,591 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:21:56,308 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:21:56,308 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:22:03,441 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:22:03,442 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:22:49,809 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:22:52,000 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 19:24:24,028 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:24:26,041 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:24:30,538 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:24:30,539 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:24:45,962 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:24:45,963 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:24:55,583 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:24:55,583 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:25:40,175 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:25:42,573 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:25:45,895 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:25:45,898 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:25:57,375 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:25:57,376 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:26:04,711 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:26:04,712 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:37:37,923 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 19:37:40,079 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:37:42,270 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:37:42,273 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:37:43,729 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:37:43,730 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:38:10,651 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:38:15,650 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:38:15,651 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:41:14,845 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:41:16,970 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:41:22,580 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:41:22,581 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:41:55,861 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:41:55,862 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
WARNING 2022-02-27 19:42:16,109 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:42:16,125 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:43:27,808 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 19:43:29,726 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 19:43:37,447 log Bad Request: /api/book/ 230
WARNING 2022-02-27 19:43:37,449 basehttp "POST /api/book/ HTTP/1.1" 400 31 161
INFO 2022-02-27 19:44:11,362 basehttp "POST /api/book/ HTTP/1.1" 201 238 161
INFO 2022-02-27 20:05:50,025 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 20:05:53,413 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 20:06:09,600 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-27 20:06:14,787 log Internal Server Error: /api/book/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2022-02-27 20:06:14,793 basehttp "POST /api/book/ HTTP/1.1" 500 81402 161
INFO 2022-02-27 20:07:16,309 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 20:07:18,547 autoreload Watching for file changes with StatReloader 637
ERROR 2022-02-27 20:07:22,115 log Internal Server Error: /api/book/ 230
Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py", line 31, in post
    serializer.is_valid(raise_exception=True)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='book with this title already exists.', code='unique')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py", line 41, in post
    return HttpResponse(e)
NameError: name 'HttpResponse' is not defined
ERROR 2022-02-27 20:07:22,195 basehttp "POST /api/book/ HTTP/1.1" 500 104473 161
INFO 2022-02-27 20:08:53,856 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 20:08:58,048 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 20:08:59,425 basehttp "POST /api/book/ HTTP/1.1" 200 86 161
INFO 2022-02-27 20:13:12,379 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 20:13:14,576 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 20:13:16,632 log Bad Request: /api/book/ 230
WARNING 2022-02-27 20:13:16,635 basehttp "POST /api/book/ HTTP/1.1" 400 45 161
INFO 2022-02-27 21:29:37,612 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\book\views.py changed, reloading. 251
INFO 2022-02-27 21:29:40,237 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 22:16:17,111 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 22:16:19,023 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 22:16:25,390 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:16:25,399 basehttp "POST /api/book/ HTTP/1.1" 400 45 161
INFO 2022-02-27 22:18:05,868 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 22:18:08,290 autoreload Watching for file changes with StatReloader 637
WARNING 2022-02-27 22:18:20,136 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:18:20,137 basehttp "POST /api/book/ HTTP/1.1" 400 37 161
WARNING 2022-02-27 22:18:31,270 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:18:31,270 basehttp "POST /api/book/ HTTP/1.1" 400 37 161
WARNING 2022-02-27 22:18:47,232 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:18:47,233 basehttp "POST /api/book/ HTTP/1.1" 400 37 161
WARNING 2022-02-27 22:18:56,117 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:18:56,118 basehttp "POST /api/book/ HTTP/1.1" 400 37 161
INFO 2022-02-27 22:19:18,221 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 22:19:20,151 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 22:20:28,676 basehttp "POST /api/book/ HTTP/1.1" 201 238 161
INFO 2022-02-27 22:20:56,735 autoreload E:\BridgeLbz\CFP_Programs\Final_BookStoreApplication\BookStoreApp\user\util.py changed, reloading. 251
INFO 2022-02-27 22:20:58,792 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 22:47:49,091 autoreload Watching for file changes with StatReloader 637
INFO 2022-02-27 22:49:59,004 basehttp "POST /api/auth/login HTTP/1.1" 202 149 161
WARNING 2022-02-27 22:50:12,424 log Bad Request: /api/auth/register/ 230
WARNING 2022-02-27 22:50:12,428 basehttp "POST /api/auth/register/ HTTP/1.1" 400 37 161
INFO 2022-02-27 22:51:03,120 basehttp "POST /api/auth/register/ HTTP/1.1" 201 35 161
ERROR 2022-02-27 22:52:25,131 views UserOTP matching query does not exist. 78
WARNING 2022-02-27 22:52:25,131 log Bad Request: /api/auth/otp-verify/ 230
WARNING 2022-02-27 22:52:25,132 basehttp "GET /api/auth/otp-verify/ HTTP/1.1" 400 32 161
INFO 2022-02-27 22:52:45,178 views Email Successfully Verified 75
INFO 2022-02-27 22:52:45,179 basehttp "GET /api/auth/otp-verify/ HTTP/1.1" 200 36 161
WARNING 2022-02-27 22:53:33,870 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:53:33,871 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-27 22:54:38,285 basehttp "POST /api/auth/login HTTP/1.1" 202 149 161
WARNING 2022-02-27 22:55:13,672 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:55:13,673 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-27 22:55:18,983 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:55:18,984 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-27 22:55:29,764 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:55:29,765 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-27 22:55:44,116 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:55:44,117 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
WARNING 2022-02-27 22:55:52,666 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:55:52,669 basehttp "DELETE /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-27 22:56:29,118 basehttp "GET /api/book/ HTTP/1.1" 201 1555 161
INFO 2022-02-27 22:57:06,848 basehttp "DELETE /api/book/ HTTP/1.1" 204 26 161
WARNING 2022-02-27 22:57:54,081 log Bad Request: /api/book/ 230
WARNING 2022-02-27 22:57:54,081 basehttp "PUT /api/book/ HTTP/1.1" 400 30 161
INFO 2022-02-27 22:58:12,218 basehttp "PUT /api/book/ HTTP/1.1" 201 220 161
INFO 2022-02-27 22:58:28,201 basehttp "PUT /api/book/ HTTP/1.1" 201 220 161
INFO 2022-02-27 22:58:40,759 basehttp "PUT /api/book/ HTTP/1.1" 201 220 161
